name: likeminds_feed_ss_fl
description: A new Flutter package project.
version: 1.1.0
publish_to: none
homepage: "https://likeminds.community/"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it:
  share_plus:
  envied:
  url_launcher:
  shared_preferences:
  simple_s3:
  flutter_bloc:
  firebase_core:
  firebase_messaging:
  overlay_support:
  lazy_load_scrollview:
  infinite_scroll_pagination:
  device_info_plus: 
  permission_handler:
  image_picker:
  file_picker:
  video_player:
  open_filex:
  timeago:
  collection:
  flick_video_player: 
  connectivity_plus:
  custom_pop_up_menu: ^1.2.4
  flutter_no_internet_widget: ^1.0.0+18-dev.1

  flutter_typeahead_mm:
    path: lib/packages/flutter_typeahead-4.3.7

  # multi_image_crop:
  #   path: lib/packages/multi_image_crop

  likeminds_feed_ui_fl:
    path: ../LikeMinds-Flutter-Feed-UI

  likeminds_feed: 1.4.0
   # path: ../LikeMinds-Flutter-Feed-SDK

dependency_override:
  sliver_tools: 0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/likeminds_feed_ss_fl/assets/icons/document.svg
    - packages/likeminds_feed_ss_fl/assets/icons/gallery.svg
    - packages/likeminds_feed_ss_fl/assets/icons/poll.svg
    - packages/likeminds_feed_ss_fl/assets/icons/video.svg
    - packages/likeminds_feed_ss_fl/assets/icons/pin.svg
    - packages/likeminds_feed_ss_fl/assets/icons/like.svg
    - packages/likeminds_feed_ss_fl/assets/icons/comment.svg
    - packages/likeminds_feed_ss_fl/assets/icons/share.svg
    - packages/likeminds_feed_ss_fl/assets/icons/like_filled.svg
    - packages/likeminds_feed_ss_fl/assets/icons/pdf.svg
    - packages/likeminds_feed_ss_fl/assets/icons/chat_lines.svg


  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
