name: likeminds_feed_ss_fl
description: A new Flutter package project.
version: 1.4.1
publish_to: none
homepage: "https://likeminds.community/"

environment:
  sdk: ">2.17.0 <3.0.0"
  flutter: ">=3.0.0 <=3.10.6"

dependencies:
  flutter:
    sdk: flutter

  get_it:
  share_plus:
  envied:
  url_launcher:
  shared_preferences:
  simple_s3: 0.3.2
  equatable:
  bloc:
  flutter_bloc:
  firebase_core:
  firebase_messaging:
  overlay_support:
  lazy_load_scrollview:
  infinite_scroll_pagination:
  device_info_plus: ^9.1.1
  permission_handler:
  image_picker:
  file_picker:
  video_player:
  open_filex:
  timeago:
  collection:
  connectivity_plus:
  custom_pop_up_menu: ^1.2.4
  flutter_no_internet_widget: ^1.0.0+18-dev.1
  extended_image: ^8.1.0
  http:
  media_kit: ^1.1.10 # Primary package.
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4

  flutter_typeahead_mm:
    path: lib/packages/flutter_typeahead-4.3.7

  likeminds_feed_ui_fl:
    path: ../LikeMinds-Flutter-Feed-UI

  likeminds_feed:
    1.6.7
    # path: ../LikeMinds-Flutter-Feed-SDK

dependency_override:
  sliver_tools: 0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/likeminds_feed_ss_fl/assets/icons/document.svg
    - packages/likeminds_feed_ss_fl/assets/icons/gallery.svg
    - packages/likeminds_feed_ss_fl/assets/icons/poll.svg
    - packages/likeminds_feed_ss_fl/assets/icons/video.svg
    - packages/likeminds_feed_ss_fl/assets/icons/pin.svg
    - packages/likeminds_feed_ss_fl/assets/icons/like.svg
    - packages/likeminds_feed_ss_fl/assets/icons/comment.svg
    - packages/likeminds_feed_ss_fl/assets/icons/share.svg
    - packages/likeminds_feed_ss_fl/assets/icons/like_filled.svg
    - packages/likeminds_feed_ss_fl/assets/icons/pdf.svg
    - packages/likeminds_feed_ss_fl/assets/icons/chat_lines.svg
    - packages/likeminds_feed_ss_fl/assets/icons/mistery-box.svg
